background = #0a0612
foreground = #d8f0ff
cursor-color = #ff2a6d
cursor-text = #0a0612
selection-background = #ea00d9
selection-foreground = #f4faff

palette = 0=#0a0612
palette = 1=#ff2a6d
palette = 2=#00ff9f
palette = 3=#f9f871
palette = 4=#0abdc6
palette = 5=#ea00d9
palette = 6=#00e5ff
palette = 7=#d8f0ff
palette = 8=#5d4a7a
palette = 9=#ff5c8a
palette = 10=#7dffc9
palette = 11=#fbffa5
palette = 12=#4fe0e8
palette = 13=#ff6bff
palette = 14=#6ff9ff
palette = 15=#f4faff