# Neo Glitch bar - neon scanline strip

[bar]
background       = "#07040c"
background-alpha = 0.92
text             = "#00ff9f"
active           = "#ea00d9"
scale-with-font  = true
size-horizontal  = 28
size-vertical    = 30